import { configureStore } from '@reduxjs/toolkit';
import {
  moduleReducer,
  messageCountReducer,
  registrationReducer,
  employeeReducer,
  captchaReducer,
  usersReducer,
  organizationReducer,
  organizationUnitReducer,
  mastersDistrictsReducer,
  mastersStatesReducer,
  designationReducer,
  groupReducer,
  ministryReducer,
  organizationTypeReducer,
  updateOrganizationReducer,
  authReducer,
  deleteOrganizationReducer,
  statisticsReducer,
  activeUserGraphReducer,
  userGraphReducer,
  messageGraphReducer,
  registrationGraphReducer,
  importEmployeeReducer,
  memberReducer,
  createorganizationUnitReducer,
  deleteOrganizationUnitReducer,
} from './authSlice';

const store = configureStore({
  reducer: {
    module: moduleReducer,
    employee: employeeReducer,
    messageCount:messageCountReducer,
    registration:registrationReducer,
    registrationGraph:registrationGraphReducer,
    activeUserGraph:activeUserGraphReducer,
    userGraph:userGraphReducer,
    messageGraph:messageGraphReducer,
    importEmployee:importEmployeeReducer,
    member:memberReducer,
    captcha:captchaReducer,
    users: usersReducer,
    statistics:statisticsReducer,
    organization: organizationReducer,
    organizationUnit: organizationUnitReducer,
    masterDistricts:mastersDistrictsReducer,
    masterStates:mastersStatesReducer,
    designation: designationReducer,
    group: groupReducer,
    ministry: ministryReducer,
    organizationType: organizationTypeReducer,
    createorganizationUnit:createorganizationUnitReducer,
    updateOrganization: updateOrganizationReducer,
    deleteOrganization:deleteOrganizationReducer,
    deleteOrganizationUnit: deleteOrganizationUnitReducer,
    auth: authReducer,
  },
});

export default store;
